// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtop.h for the primary calling header

#ifndef VERILATED_VTOP_P_CSA_TOTAL_H_
#define VERILATED_VTOP_P_CSA_TOTAL_H_  // guard

#include "verilated.h"


class Vtop__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vtop_p_CSA_Total final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN16(io_in_0,8,0);
        VL_IN16(io_in_1,8,0);
        VL_IN16(io_in_2,8,0);
        VL_IN16(io_in_3,8,0);
        VL_IN16(io_in_4,8,0);
        VL_IN16(io_in_5,8,0);
        VL_IN16(io_in_6,8,0);
        VL_IN16(io_in_7,8,0);
        VL_IN16(io_in_8,8,0);
        VL_IN16(io_in_9,8,0);
        VL_IN16(io_in_10,8,0);
        VL_IN16(io_in_11,8,0);
        VL_IN16(io_in_12,8,0);
        VL_IN16(io_in_13,8,0);
        VL_IN16(io_in_14,8,0);
        VL_IN16(io_in_15,8,0);
        VL_IN16(io_in_16,8,0);
        VL_IN16(io_in_17,8,0);
        VL_IN16(io_in_18,8,0);
        VL_IN16(io_in_19,8,0);
        VL_IN16(io_in_20,8,0);
        VL_IN16(io_in_21,8,0);
        VL_IN16(io_in_22,8,0);
        VL_IN16(io_in_23,8,0);
        VL_IN16(io_in_24,8,0);
        VL_IN16(io_in_25,8,0);
        VL_IN16(io_in_26,8,0);
        VL_IN16(io_in_27,8,0);
        VL_IN16(io_in_28,8,0);
        VL_IN16(io_in_29,8,0);
        VL_IN16(io_in_30,8,0);
        VL_IN16(io_in_31,8,0);
        VL_OUT16(io_out_0,13,0);
        VL_OUT16(io_out_1,13,0);
        SData/*13:0*/ _stage_6_io_out_0;
        SData/*13:0*/ _stage_6_io_out_1;
        SData/*13:0*/ _stage_6_io_out_2;
        SData/*13:0*/ _stage_5_io_out_0;
        SData/*13:0*/ _stage_5_io_out_1;
        SData/*13:0*/ _stage_5_io_out_2;
        SData/*13:0*/ _stage_5_io_out_3;
        SData/*13:0*/ _stage_4_io_out_0;
        SData/*13:0*/ _stage_4_io_out_1;
        SData/*13:0*/ _stage_4_io_out_2;
        SData/*13:0*/ _stage_4_io_out_3;
        SData/*13:0*/ _stage_4_io_out_4;
        SData/*12:0*/ _stage_3_io_out_0;
        SData/*12:0*/ _stage_3_io_out_1;
        SData/*12:0*/ _stage_3_io_out_2;
        SData/*12:0*/ _stage_3_io_out_3;
        SData/*12:0*/ _stage_3_io_out_4;
        SData/*12:0*/ _stage_3_io_out_5;
        SData/*12:0*/ _stage_3_io_out_6;
        SData/*11:0*/ _stage_2_io_out_0;
        SData/*11:0*/ _stage_2_io_out_1;
        SData/*11:0*/ _stage_2_io_out_2;
        SData/*11:0*/ _stage_2_io_out_3;
        SData/*11:0*/ _stage_2_io_out_4;
        SData/*11:0*/ _stage_2_io_out_5;
        SData/*11:0*/ _stage_2_io_out_6;
        SData/*11:0*/ _stage_2_io_out_7;
        SData/*11:0*/ _stage_2_io_out_8;
        SData/*11:0*/ _stage_2_io_out_9;
        SData/*10:0*/ _stage_1_io_out_0;
    };
    struct {
        SData/*10:0*/ _stage_1_io_out_1;
        SData/*10:0*/ _stage_1_io_out_2;
        SData/*10:0*/ _stage_1_io_out_3;
        SData/*10:0*/ _stage_1_io_out_4;
        SData/*10:0*/ _stage_1_io_out_5;
        SData/*10:0*/ _stage_1_io_out_6;
        SData/*10:0*/ _stage_1_io_out_7;
        SData/*10:0*/ _stage_1_io_out_8;
        SData/*10:0*/ _stage_1_io_out_9;
        SData/*10:0*/ _stage_1_io_out_10;
        SData/*10:0*/ _stage_1_io_out_11;
        SData/*10:0*/ _stage_1_io_out_12;
        SData/*10:0*/ _stage_1_io_out_13;
        SData/*10:0*/ _stage_1_io_out_14;
        SData/*9:0*/ _stage_io_out_0;
        SData/*9:0*/ _stage_io_out_1;
        SData/*9:0*/ _stage_io_out_2;
        SData/*9:0*/ _stage_io_out_3;
        SData/*9:0*/ _stage_io_out_4;
        SData/*9:0*/ _stage_io_out_5;
        SData/*9:0*/ _stage_io_out_6;
        SData/*9:0*/ _stage_io_out_7;
        SData/*9:0*/ _stage_io_out_8;
        SData/*9:0*/ _stage_io_out_9;
        SData/*9:0*/ _stage_io_out_10;
        SData/*9:0*/ _stage_io_out_11;
        SData/*9:0*/ _stage_io_out_12;
        SData/*9:0*/ _stage_io_out_13;
        SData/*9:0*/ _stage_io_out_14;
        SData/*9:0*/ _stage_io_out_15;
        SData/*9:0*/ _stage_io_out_16;
        SData/*9:0*/ _stage_io_out_17;
        SData/*9:0*/ _stage_io_out_18;
        SData/*9:0*/ _stage_io_out_19;
        SData/*9:0*/ _stage_io_out_20;
        SData/*9:0*/ _stage_io_out_21;
        SData/*8:0*/ stage__DOT__io_in_0;
        SData/*8:0*/ stage__DOT__io_in_1;
        SData/*8:0*/ stage__DOT__io_in_2;
        SData/*8:0*/ stage__DOT__io_in_3;
        SData/*8:0*/ stage__DOT__io_in_4;
        SData/*8:0*/ stage__DOT__io_in_5;
        SData/*8:0*/ stage__DOT__io_in_6;
        SData/*8:0*/ stage__DOT__io_in_7;
        SData/*8:0*/ stage__DOT__io_in_8;
        SData/*8:0*/ stage__DOT__io_in_9;
        SData/*8:0*/ stage__DOT__io_in_10;
        SData/*8:0*/ stage__DOT__io_in_11;
        SData/*8:0*/ stage__DOT__io_in_12;
        SData/*8:0*/ stage__DOT__io_in_13;
        SData/*8:0*/ stage__DOT__io_in_14;
        SData/*8:0*/ stage__DOT__io_in_15;
        SData/*8:0*/ stage__DOT__io_in_16;
        SData/*8:0*/ stage__DOT__io_in_17;
        SData/*8:0*/ stage__DOT__io_in_18;
        SData/*8:0*/ stage__DOT__io_in_19;
        SData/*8:0*/ stage__DOT__io_in_20;
        SData/*8:0*/ stage__DOT__io_in_21;
        SData/*8:0*/ stage__DOT__io_in_22;
        SData/*8:0*/ stage__DOT__io_in_23;
        SData/*8:0*/ stage__DOT__io_in_24;
        SData/*8:0*/ stage__DOT__io_in_25;
        SData/*8:0*/ stage__DOT__io_in_26;
        SData/*8:0*/ stage__DOT__io_in_27;
    };
    struct {
        SData/*8:0*/ stage__DOT__io_in_28;
        SData/*8:0*/ stage__DOT__io_in_29;
        SData/*8:0*/ stage__DOT__io_in_30;
        SData/*8:0*/ stage__DOT__io_in_31;
        SData/*9:0*/ stage__DOT__io_out_0;
        SData/*9:0*/ stage__DOT__io_out_1;
        SData/*9:0*/ stage__DOT__io_out_2;
        SData/*9:0*/ stage__DOT__io_out_3;
        SData/*9:0*/ stage__DOT__io_out_4;
        SData/*9:0*/ stage__DOT__io_out_5;
        SData/*9:0*/ stage__DOT__io_out_6;
        SData/*9:0*/ stage__DOT__io_out_7;
        SData/*9:0*/ stage__DOT__io_out_8;
        SData/*9:0*/ stage__DOT__io_out_9;
        SData/*9:0*/ stage__DOT__io_out_10;
        SData/*9:0*/ stage__DOT__io_out_11;
        SData/*9:0*/ stage__DOT__io_out_12;
        SData/*9:0*/ stage__DOT__io_out_13;
        SData/*9:0*/ stage__DOT__io_out_14;
        SData/*9:0*/ stage__DOT__io_out_15;
        SData/*9:0*/ stage__DOT__io_out_16;
        SData/*9:0*/ stage__DOT__io_out_17;
        SData/*9:0*/ stage__DOT__io_out_18;
        SData/*9:0*/ stage__DOT__io_out_19;
        SData/*9:0*/ stage__DOT__io_out_20;
        SData/*9:0*/ stage__DOT__io_out_21;
        SData/*8:0*/ stage__DOT___units_9_io_sum;
        SData/*8:0*/ stage__DOT___units_9_io_carry;
        SData/*8:0*/ stage__DOT___units_8_io_sum;
        SData/*8:0*/ stage__DOT___units_8_io_carry;
        SData/*8:0*/ stage__DOT___units_7_io_sum;
        SData/*8:0*/ stage__DOT___units_7_io_carry;
        SData/*8:0*/ stage__DOT___units_6_io_sum;
        SData/*8:0*/ stage__DOT___units_6_io_carry;
        SData/*8:0*/ stage__DOT___units_5_io_sum;
        SData/*8:0*/ stage__DOT___units_5_io_carry;
        SData/*8:0*/ stage__DOT___units_4_io_sum;
        SData/*8:0*/ stage__DOT___units_4_io_carry;
        SData/*8:0*/ stage__DOT___units_3_io_sum;
        SData/*8:0*/ stage__DOT___units_3_io_carry;
        SData/*8:0*/ stage__DOT___units_2_io_sum;
        SData/*8:0*/ stage__DOT___units_2_io_carry;
        SData/*8:0*/ stage__DOT___units_1_io_sum;
        SData/*8:0*/ stage__DOT___units_1_io_carry;
        SData/*8:0*/ stage__DOT___units_0_io_sum;
        SData/*8:0*/ stage__DOT___units_0_io_carry;
        SData/*8:0*/ stage__DOT__units_0__DOT__io_in_0;
        SData/*8:0*/ stage__DOT__units_0__DOT__io_in_1;
        SData/*8:0*/ stage__DOT__units_0__DOT__io_in_2;
        SData/*8:0*/ stage__DOT__units_0__DOT__io_sum;
        SData/*8:0*/ stage__DOT__units_0__DOT__io_carry;
        SData/*8:0*/ stage__DOT__units_1__DOT__io_in_0;
        SData/*8:0*/ stage__DOT__units_1__DOT__io_in_1;
        SData/*8:0*/ stage__DOT__units_1__DOT__io_in_2;
        SData/*8:0*/ stage__DOT__units_1__DOT__io_sum;
        SData/*8:0*/ stage__DOT__units_1__DOT__io_carry;
        SData/*8:0*/ stage__DOT__units_2__DOT__io_in_0;
        SData/*8:0*/ stage__DOT__units_2__DOT__io_in_1;
        SData/*8:0*/ stage__DOT__units_2__DOT__io_in_2;
        SData/*8:0*/ stage__DOT__units_2__DOT__io_sum;
        SData/*8:0*/ stage__DOT__units_2__DOT__io_carry;
        SData/*8:0*/ stage__DOT__units_3__DOT__io_in_0;
        SData/*8:0*/ stage__DOT__units_3__DOT__io_in_1;
        SData/*8:0*/ stage__DOT__units_3__DOT__io_in_2;
    };
    struct {
        SData/*8:0*/ stage__DOT__units_3__DOT__io_sum;
        SData/*8:0*/ stage__DOT__units_3__DOT__io_carry;
        SData/*8:0*/ stage__DOT__units_4__DOT__io_in_0;
        SData/*8:0*/ stage__DOT__units_4__DOT__io_in_1;
        SData/*8:0*/ stage__DOT__units_4__DOT__io_in_2;
        SData/*8:0*/ stage__DOT__units_4__DOT__io_sum;
        SData/*8:0*/ stage__DOT__units_4__DOT__io_carry;
        SData/*8:0*/ stage__DOT__units_5__DOT__io_in_0;
        SData/*8:0*/ stage__DOT__units_5__DOT__io_in_1;
        SData/*8:0*/ stage__DOT__units_5__DOT__io_in_2;
        SData/*8:0*/ stage__DOT__units_5__DOT__io_sum;
        SData/*8:0*/ stage__DOT__units_5__DOT__io_carry;
        SData/*8:0*/ stage__DOT__units_6__DOT__io_in_0;
        SData/*8:0*/ stage__DOT__units_6__DOT__io_in_1;
        SData/*8:0*/ stage__DOT__units_6__DOT__io_in_2;
        SData/*8:0*/ stage__DOT__units_6__DOT__io_sum;
        SData/*8:0*/ stage__DOT__units_6__DOT__io_carry;
        SData/*8:0*/ stage__DOT__units_7__DOT__io_in_0;
        SData/*8:0*/ stage__DOT__units_7__DOT__io_in_1;
        SData/*8:0*/ stage__DOT__units_7__DOT__io_in_2;
        SData/*8:0*/ stage__DOT__units_7__DOT__io_sum;
        SData/*8:0*/ stage__DOT__units_7__DOT__io_carry;
        SData/*8:0*/ stage__DOT__units_8__DOT__io_in_0;
        SData/*8:0*/ stage__DOT__units_8__DOT__io_in_1;
        SData/*8:0*/ stage__DOT__units_8__DOT__io_in_2;
        SData/*8:0*/ stage__DOT__units_8__DOT__io_sum;
        SData/*8:0*/ stage__DOT__units_8__DOT__io_carry;
        SData/*8:0*/ stage__DOT__units_9__DOT__io_in_0;
        SData/*8:0*/ stage__DOT__units_9__DOT__io_in_1;
        SData/*8:0*/ stage__DOT__units_9__DOT__io_in_2;
        SData/*8:0*/ stage__DOT__units_9__DOT__io_sum;
        SData/*8:0*/ stage__DOT__units_9__DOT__io_carry;
        SData/*9:0*/ stage_1__DOT__io_in_0;
        SData/*9:0*/ stage_1__DOT__io_in_1;
        SData/*9:0*/ stage_1__DOT__io_in_2;
        SData/*9:0*/ stage_1__DOT__io_in_3;
        SData/*9:0*/ stage_1__DOT__io_in_4;
        SData/*9:0*/ stage_1__DOT__io_in_5;
        SData/*9:0*/ stage_1__DOT__io_in_6;
        SData/*9:0*/ stage_1__DOT__io_in_7;
        SData/*9:0*/ stage_1__DOT__io_in_8;
        SData/*9:0*/ stage_1__DOT__io_in_9;
        SData/*9:0*/ stage_1__DOT__io_in_10;
        SData/*9:0*/ stage_1__DOT__io_in_11;
        SData/*9:0*/ stage_1__DOT__io_in_12;
        SData/*9:0*/ stage_1__DOT__io_in_13;
        SData/*9:0*/ stage_1__DOT__io_in_14;
        SData/*9:0*/ stage_1__DOT__io_in_15;
        SData/*9:0*/ stage_1__DOT__io_in_16;
        SData/*9:0*/ stage_1__DOT__io_in_17;
        SData/*9:0*/ stage_1__DOT__io_in_18;
        SData/*9:0*/ stage_1__DOT__io_in_19;
        SData/*9:0*/ stage_1__DOT__io_in_20;
        SData/*9:0*/ stage_1__DOT__io_in_21;
        SData/*10:0*/ stage_1__DOT__io_out_0;
        SData/*10:0*/ stage_1__DOT__io_out_1;
        SData/*10:0*/ stage_1__DOT__io_out_2;
        SData/*10:0*/ stage_1__DOT__io_out_3;
        SData/*10:0*/ stage_1__DOT__io_out_4;
        SData/*10:0*/ stage_1__DOT__io_out_5;
        SData/*10:0*/ stage_1__DOT__io_out_6;
        SData/*10:0*/ stage_1__DOT__io_out_7;
        SData/*10:0*/ stage_1__DOT__io_out_8;
        SData/*10:0*/ stage_1__DOT__io_out_9;
    };
    struct {
        SData/*10:0*/ stage_1__DOT__io_out_10;
        SData/*10:0*/ stage_1__DOT__io_out_11;
        SData/*10:0*/ stage_1__DOT__io_out_12;
        SData/*10:0*/ stage_1__DOT__io_out_13;
        SData/*10:0*/ stage_1__DOT__io_out_14;
        SData/*9:0*/ stage_1__DOT___units_6_io_sum;
        SData/*9:0*/ stage_1__DOT___units_6_io_carry;
        SData/*9:0*/ stage_1__DOT___units_5_io_sum;
        SData/*9:0*/ stage_1__DOT___units_5_io_carry;
        SData/*9:0*/ stage_1__DOT___units_4_io_sum;
        SData/*9:0*/ stage_1__DOT___units_4_io_carry;
        SData/*9:0*/ stage_1__DOT___units_3_io_sum;
        SData/*9:0*/ stage_1__DOT___units_3_io_carry;
        SData/*9:0*/ stage_1__DOT___units_2_io_sum;
        SData/*9:0*/ stage_1__DOT___units_2_io_carry;
        SData/*9:0*/ stage_1__DOT___units_1_io_sum;
        SData/*9:0*/ stage_1__DOT___units_1_io_carry;
        SData/*9:0*/ stage_1__DOT___units_0_io_sum;
        SData/*9:0*/ stage_1__DOT___units_0_io_carry;
        SData/*9:0*/ stage_1__DOT__units_0__DOT__io_in_0;
        SData/*9:0*/ stage_1__DOT__units_0__DOT__io_in_1;
        SData/*9:0*/ stage_1__DOT__units_0__DOT__io_in_2;
        SData/*9:0*/ stage_1__DOT__units_0__DOT__io_sum;
        SData/*9:0*/ stage_1__DOT__units_0__DOT__io_carry;
        SData/*9:0*/ stage_1__DOT__units_1__DOT__io_in_0;
        SData/*9:0*/ stage_1__DOT__units_1__DOT__io_in_1;
        SData/*9:0*/ stage_1__DOT__units_1__DOT__io_in_2;
        SData/*9:0*/ stage_1__DOT__units_1__DOT__io_sum;
        SData/*9:0*/ stage_1__DOT__units_1__DOT__io_carry;
        SData/*9:0*/ stage_1__DOT__units_2__DOT__io_in_0;
        SData/*9:0*/ stage_1__DOT__units_2__DOT__io_in_1;
        SData/*9:0*/ stage_1__DOT__units_2__DOT__io_in_2;
        SData/*9:0*/ stage_1__DOT__units_2__DOT__io_sum;
        SData/*9:0*/ stage_1__DOT__units_2__DOT__io_carry;
        SData/*9:0*/ stage_1__DOT__units_3__DOT__io_in_0;
        SData/*9:0*/ stage_1__DOT__units_3__DOT__io_in_1;
        SData/*9:0*/ stage_1__DOT__units_3__DOT__io_in_2;
        SData/*9:0*/ stage_1__DOT__units_3__DOT__io_sum;
        SData/*9:0*/ stage_1__DOT__units_3__DOT__io_carry;
        SData/*9:0*/ stage_1__DOT__units_4__DOT__io_in_0;
        SData/*9:0*/ stage_1__DOT__units_4__DOT__io_in_1;
        SData/*9:0*/ stage_1__DOT__units_4__DOT__io_in_2;
        SData/*9:0*/ stage_1__DOT__units_4__DOT__io_sum;
        SData/*9:0*/ stage_1__DOT__units_4__DOT__io_carry;
        SData/*9:0*/ stage_1__DOT__units_5__DOT__io_in_0;
        SData/*9:0*/ stage_1__DOT__units_5__DOT__io_in_1;
        SData/*9:0*/ stage_1__DOT__units_5__DOT__io_in_2;
        SData/*9:0*/ stage_1__DOT__units_5__DOT__io_sum;
        SData/*9:0*/ stage_1__DOT__units_5__DOT__io_carry;
        SData/*9:0*/ stage_1__DOT__units_6__DOT__io_in_0;
        SData/*9:0*/ stage_1__DOT__units_6__DOT__io_in_1;
        SData/*9:0*/ stage_1__DOT__units_6__DOT__io_in_2;
        SData/*9:0*/ stage_1__DOT__units_6__DOT__io_sum;
        SData/*9:0*/ stage_1__DOT__units_6__DOT__io_carry;
        SData/*10:0*/ stage_2__DOT__io_in_0;
        SData/*10:0*/ stage_2__DOT__io_in_1;
        SData/*10:0*/ stage_2__DOT__io_in_2;
        SData/*10:0*/ stage_2__DOT__io_in_3;
        SData/*10:0*/ stage_2__DOT__io_in_4;
        SData/*10:0*/ stage_2__DOT__io_in_5;
        SData/*10:0*/ stage_2__DOT__io_in_6;
        SData/*10:0*/ stage_2__DOT__io_in_7;
        SData/*10:0*/ stage_2__DOT__io_in_8;
        SData/*10:0*/ stage_2__DOT__io_in_9;
    };
    struct {
        SData/*10:0*/ stage_2__DOT__io_in_10;
        SData/*10:0*/ stage_2__DOT__io_in_11;
        SData/*10:0*/ stage_2__DOT__io_in_12;
        SData/*10:0*/ stage_2__DOT__io_in_13;
        SData/*10:0*/ stage_2__DOT__io_in_14;
        SData/*11:0*/ stage_2__DOT__io_out_0;
        SData/*11:0*/ stage_2__DOT__io_out_1;
        SData/*11:0*/ stage_2__DOT__io_out_2;
        SData/*11:0*/ stage_2__DOT__io_out_3;
        SData/*11:0*/ stage_2__DOT__io_out_4;
        SData/*11:0*/ stage_2__DOT__io_out_5;
        SData/*11:0*/ stage_2__DOT__io_out_6;
        SData/*11:0*/ stage_2__DOT__io_out_7;
        SData/*11:0*/ stage_2__DOT__io_out_8;
        SData/*11:0*/ stage_2__DOT__io_out_9;
        SData/*10:0*/ stage_2__DOT___units_4_io_sum;
        SData/*10:0*/ stage_2__DOT___units_4_io_carry;
        SData/*10:0*/ stage_2__DOT___units_3_io_sum;
        SData/*10:0*/ stage_2__DOT___units_3_io_carry;
        SData/*10:0*/ stage_2__DOT___units_2_io_sum;
        SData/*10:0*/ stage_2__DOT___units_2_io_carry;
        SData/*10:0*/ stage_2__DOT___units_1_io_sum;
        SData/*10:0*/ stage_2__DOT___units_1_io_carry;
        SData/*10:0*/ stage_2__DOT___units_0_io_sum;
        SData/*10:0*/ stage_2__DOT___units_0_io_carry;
        SData/*10:0*/ stage_2__DOT__units_0__DOT__io_in_0;
        SData/*10:0*/ stage_2__DOT__units_0__DOT__io_in_1;
        SData/*10:0*/ stage_2__DOT__units_0__DOT__io_in_2;
        SData/*10:0*/ stage_2__DOT__units_0__DOT__io_sum;
        SData/*10:0*/ stage_2__DOT__units_0__DOT__io_carry;
        SData/*10:0*/ stage_2__DOT__units_1__DOT__io_in_0;
        SData/*10:0*/ stage_2__DOT__units_1__DOT__io_in_1;
        SData/*10:0*/ stage_2__DOT__units_1__DOT__io_in_2;
        SData/*10:0*/ stage_2__DOT__units_1__DOT__io_sum;
        SData/*10:0*/ stage_2__DOT__units_1__DOT__io_carry;
        SData/*10:0*/ stage_2__DOT__units_2__DOT__io_in_0;
        SData/*10:0*/ stage_2__DOT__units_2__DOT__io_in_1;
        SData/*10:0*/ stage_2__DOT__units_2__DOT__io_in_2;
        SData/*10:0*/ stage_2__DOT__units_2__DOT__io_sum;
        SData/*10:0*/ stage_2__DOT__units_2__DOT__io_carry;
        SData/*10:0*/ stage_2__DOT__units_3__DOT__io_in_0;
        SData/*10:0*/ stage_2__DOT__units_3__DOT__io_in_1;
        SData/*10:0*/ stage_2__DOT__units_3__DOT__io_in_2;
        SData/*10:0*/ stage_2__DOT__units_3__DOT__io_sum;
        SData/*10:0*/ stage_2__DOT__units_3__DOT__io_carry;
        SData/*10:0*/ stage_2__DOT__units_4__DOT__io_in_0;
        SData/*10:0*/ stage_2__DOT__units_4__DOT__io_in_1;
        SData/*10:0*/ stage_2__DOT__units_4__DOT__io_in_2;
        SData/*10:0*/ stage_2__DOT__units_4__DOT__io_sum;
        SData/*10:0*/ stage_2__DOT__units_4__DOT__io_carry;
        SData/*11:0*/ stage_3__DOT__io_in_0;
        SData/*11:0*/ stage_3__DOT__io_in_1;
        SData/*11:0*/ stage_3__DOT__io_in_2;
        SData/*11:0*/ stage_3__DOT__io_in_3;
        SData/*11:0*/ stage_3__DOT__io_in_4;
        SData/*11:0*/ stage_3__DOT__io_in_5;
        SData/*11:0*/ stage_3__DOT__io_in_6;
        SData/*11:0*/ stage_3__DOT__io_in_7;
        SData/*11:0*/ stage_3__DOT__io_in_8;
        SData/*11:0*/ stage_3__DOT__io_in_9;
        SData/*12:0*/ stage_3__DOT__io_out_0;
        SData/*12:0*/ stage_3__DOT__io_out_1;
        SData/*12:0*/ stage_3__DOT__io_out_2;
        SData/*12:0*/ stage_3__DOT__io_out_3;
    };
    struct {
        SData/*12:0*/ stage_3__DOT__io_out_4;
        SData/*12:0*/ stage_3__DOT__io_out_5;
        SData/*12:0*/ stage_3__DOT__io_out_6;
        SData/*11:0*/ stage_3__DOT___units_2_io_sum;
        SData/*11:0*/ stage_3__DOT___units_2_io_carry;
        SData/*11:0*/ stage_3__DOT___units_1_io_sum;
        SData/*11:0*/ stage_3__DOT___units_1_io_carry;
        SData/*11:0*/ stage_3__DOT___units_0_io_sum;
        SData/*11:0*/ stage_3__DOT___units_0_io_carry;
        SData/*11:0*/ stage_3__DOT__units_0__DOT__io_in_0;
        SData/*11:0*/ stage_3__DOT__units_0__DOT__io_in_1;
        SData/*11:0*/ stage_3__DOT__units_0__DOT__io_in_2;
        SData/*11:0*/ stage_3__DOT__units_0__DOT__io_sum;
        SData/*11:0*/ stage_3__DOT__units_0__DOT__io_carry;
        SData/*11:0*/ stage_3__DOT__units_1__DOT__io_in_0;
        SData/*11:0*/ stage_3__DOT__units_1__DOT__io_in_1;
        SData/*11:0*/ stage_3__DOT__units_1__DOT__io_in_2;
        SData/*11:0*/ stage_3__DOT__units_1__DOT__io_sum;
        SData/*11:0*/ stage_3__DOT__units_1__DOT__io_carry;
        SData/*11:0*/ stage_3__DOT__units_2__DOT__io_in_0;
        SData/*11:0*/ stage_3__DOT__units_2__DOT__io_in_1;
        SData/*11:0*/ stage_3__DOT__units_2__DOT__io_in_2;
        SData/*11:0*/ stage_3__DOT__units_2__DOT__io_sum;
        SData/*11:0*/ stage_3__DOT__units_2__DOT__io_carry;
        SData/*12:0*/ stage_4__DOT__io_in_0;
        SData/*12:0*/ stage_4__DOT__io_in_1;
        SData/*12:0*/ stage_4__DOT__io_in_2;
        SData/*12:0*/ stage_4__DOT__io_in_3;
        SData/*12:0*/ stage_4__DOT__io_in_4;
        SData/*12:0*/ stage_4__DOT__io_in_5;
        SData/*12:0*/ stage_4__DOT__io_in_6;
        SData/*13:0*/ stage_4__DOT__io_out_0;
        SData/*13:0*/ stage_4__DOT__io_out_1;
        SData/*13:0*/ stage_4__DOT__io_out_2;
        SData/*13:0*/ stage_4__DOT__io_out_3;
        SData/*13:0*/ stage_4__DOT__io_out_4;
        SData/*12:0*/ stage_4__DOT___units_1_io_sum;
        SData/*12:0*/ stage_4__DOT___units_1_io_carry;
        SData/*12:0*/ stage_4__DOT___units_0_io_sum;
        SData/*12:0*/ stage_4__DOT___units_0_io_carry;
        SData/*12:0*/ stage_4__DOT__units_0__DOT__io_in_0;
        SData/*12:0*/ stage_4__DOT__units_0__DOT__io_in_1;
        SData/*12:0*/ stage_4__DOT__units_0__DOT__io_in_2;
        SData/*12:0*/ stage_4__DOT__units_0__DOT__io_sum;
        SData/*12:0*/ stage_4__DOT__units_0__DOT__io_carry;
        SData/*12:0*/ stage_4__DOT__units_1__DOT__io_in_0;
        SData/*12:0*/ stage_4__DOT__units_1__DOT__io_in_1;
        SData/*12:0*/ stage_4__DOT__units_1__DOT__io_in_2;
        SData/*12:0*/ stage_4__DOT__units_1__DOT__io_sum;
        SData/*12:0*/ stage_4__DOT__units_1__DOT__io_carry;
        SData/*13:0*/ stage_5__DOT__io_in_0;
        SData/*13:0*/ stage_5__DOT__io_in_1;
        SData/*13:0*/ stage_5__DOT__io_in_2;
        SData/*13:0*/ stage_5__DOT__io_in_3;
        SData/*13:0*/ stage_5__DOT__io_in_4;
        SData/*13:0*/ stage_5__DOT__io_out_0;
        SData/*13:0*/ stage_5__DOT__io_out_1;
        SData/*13:0*/ stage_5__DOT__io_out_2;
        SData/*13:0*/ stage_5__DOT__io_out_3;
        SData/*13:0*/ stage_5__DOT___units_0_io_carry;
        SData/*13:0*/ stage_5__DOT__units_0__DOT__io_in_0;
        SData/*13:0*/ stage_5__DOT__units_0__DOT__io_in_1;
        SData/*13:0*/ stage_5__DOT__units_0__DOT__io_in_2;
        SData/*13:0*/ stage_5__DOT__units_0__DOT__io_sum;
    };
    struct {
        SData/*13:0*/ stage_5__DOT__units_0__DOT__io_carry;
        SData/*13:0*/ stage_6__DOT__io_in_0;
        SData/*13:0*/ stage_6__DOT__io_in_1;
        SData/*13:0*/ stage_6__DOT__io_in_2;
        SData/*13:0*/ stage_6__DOT__io_in_3;
        SData/*13:0*/ stage_6__DOT__io_out_0;
        SData/*13:0*/ stage_6__DOT__io_out_1;
        SData/*13:0*/ stage_6__DOT__io_out_2;
        SData/*13:0*/ stage_6__DOT___units_0_io_carry;
        SData/*13:0*/ stage_6__DOT__units_0__DOT__io_in_0;
        SData/*13:0*/ stage_6__DOT__units_0__DOT__io_in_1;
        SData/*13:0*/ stage_6__DOT__units_0__DOT__io_in_2;
        SData/*13:0*/ stage_6__DOT__units_0__DOT__io_sum;
        SData/*13:0*/ stage_6__DOT__units_0__DOT__io_carry;
        SData/*13:0*/ stage_7__DOT__io_in_0;
        SData/*13:0*/ stage_7__DOT__io_in_1;
        SData/*13:0*/ stage_7__DOT__io_in_2;
        SData/*13:0*/ stage_7__DOT__io_out_0;
        SData/*13:0*/ stage_7__DOT__io_out_1;
        SData/*13:0*/ stage_7__DOT___units_0_io_carry;
        SData/*13:0*/ stage_7__DOT__units_0__DOT__io_in_0;
        SData/*13:0*/ stage_7__DOT__units_0__DOT__io_in_1;
        SData/*13:0*/ stage_7__DOT__units_0__DOT__io_in_2;
        SData/*13:0*/ stage_7__DOT__units_0__DOT__io_sum;
        SData/*13:0*/ stage_7__DOT__units_0__DOT__io_carry;
    };

    // INTERNAL VARIABLES
    Vtop__Syms* const vlSymsp;

    // CONSTRUCTORS
    Vtop_p_CSA_Total(Vtop__Syms* symsp, const char* v__name);
    ~Vtop_p_CSA_Total();
    VL_UNCOPYABLE(Vtop_p_CSA_Total);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
